### ISSUE TITLE
服务端启动报ERR Client sent AUTH, but no password is set

### ISSUE THREAD

**Issue by ghzengqy568** [baidu/brcc#29]
org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to x.x.x.x:x
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$ExceptionTranslatingConnectionProvider.translateException(LettuceConnectionFactory.java:1553) ~[spring-data-redis-2.4.1.jar:2.4.1]
....
Caused by: io.lettuce.core.RedisCommandExecutionException: ERR Client sent AUTH, but no password is set
	at io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:137) ~[lettuce-core-6.0.1.RELEASE.jar:6.0.1.RELEASE]
	at io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:110) ~[lettuce-core-6.0.1.RELEASE.jar:6.0.1.RELEASE]
	at io.lettuce.core.protocol.AsyncCommand.completeResult(AsyncCommand.java:120) ~[lettuce-core-6.0.1.RELEASE.jar:6.0.1.RELEASE]

**Comment by ghzengqy568** [comment]
后端服务连接redis过程中提供了密码访问， 如果你的redis 不需要密码访问，而又提供了spring.redis.password， 此时将会导致RedisConnectionFailureException异常， 希望在application.yml中去掉spring.redis.password配置项， 有不同环境（如application-dev.yml）根据自己环境决定添加spring.redis.password配置
